{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clockwork-api.fullname" . }}-redis
  labels:
    {{- include "clockwork-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "clockwork-api.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
