{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clockwork-api.fullname" . }}-redis
  labels:
    {{- include "clockwork-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_URL: {{ if .Values.redis.auth.enabled }}{{ printf "redis://:%s@%s-redis:%v" .Values.redis.auth.password (include "clockwork-api.fullname" .) .Values.redis.service.port | quote }}{{ else }}{{ printf "redis://%s-redis:%v" (include "clockwork-api.fullname" .) .Values.redis.service.port | quote }}{{ end }}
  {{- if .Values.redis.auth.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  {{- end }}
{{- end }}
