{{- if gt (len .Values.secretEnv) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clockwork-api.fullname" . }}-secret
  labels:
    {{- include "clockwork-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
